name: Kernel CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: 11451419190810
        max-size: 1536M
    - name: Setup LLVM
      run: |
        sudo apt-get install curl bison flex make binutils dwarves git lld pahole zip perl make gcc python3 python-is-python3 bc libssl-dev libelf-dev clang -y
    - name: Configure
      run: make CC="ccache clang" LD=ld.lld HOSTCC="ccache clang" O=out KCFLAGS+=-Wno-error gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config -j8
    - name: Build
      run: make CC="ccache clang" LD=ld.lld HOSTCC="ccache clang" O=out KCFLAGS+=-Wno-error all -j8
      
